### PR TITLE
Have a single point where triangulate is called.

### PR DESCRIPTION
**Pull request by j-fu**
Hi, very nice work! However I have a different use case which is not covered by your lib so far. (see VoronoiFVM.jl) So I suggest this pull request which allows me to call triangulate directly and "do what I want". Once it's there, one could think about  a single Julia wrapper for all calls to Triangle.

Jürgen

### CODE REVIEW

**Comment by konsim83** [comment]
Hi Juergen,
Yes, that is indeed useful. Thumbs up for the initiative. :-)
Best,
Konrad

**Comment by j-fu** [comment]
Hi thanks!
While waiting for the merge  I was in doubt if you like this. So I worked on an idea to have essentially a 1:1 correspondence between C and Julia. See [triangle.jl](https://github.com/j-fu/VoronoiFVM.jl/blob/master/src/triangle/triangle.jl) . It currently sits in VoronoiFVM.jl (which is my use case for Triangle). If you wish I we can integrate this into your package as I believe it makes no sense to create the n+1st triangle package. Otherwise I would make a couple more suggestions for your package based on the current structure.

Jürgen

**Comment by konsim83** [comment]
Sure, any contribution to increase the functionality and usability for other people are welcome. That's why I put it online in the first place, so other people can benefit from my implementation. The only thing I kindly like to ask for is a documentation in the style the functions are documented in the original code so that the new code will be visible in the documentation which is automatically pushed and updated. Just makes it easier for users.
Best,
Konrad

**Comment by j-fu** [comment]
Hi, I might try this. OTOH we might also try to consolidate the triangle in Julia also with Triangle.jl, see the discussion [on neutral ground](https://github.com/j-fu/VoronoiFVM.jl/issues/2).

Jürgen

**Pull request merged**
